### PR TITLE
Mass updates and related code migrations/type fixes

### PR DESCRIPTION
**Pull request by rosskevin**
I tried to keep all intents the same.  I note there is no eslint config.

- update all libraries
- migrate away from deprecated `vscode` to `vscode-test` and `@types/vscode`
- update type errors
- remove some deprecated code to fix warnings

Scripts:
- add `build` script (no watch)
- move `compile` to `build:watch`
- add `package` scripts to use `vsce` in a way that allows for modern yarn use 
- add convenience `package:install` for local dev use
- add `deploy` scripts

#49

I'm not familiar with writing/testing vscode extensions, so this should be reviewed before merging.

Related:
- yarn v2+ not supported by vsce https://github.com/microsoft/vscode-vsce/issues/517
- draw yarn fix inspiration and packaging scripts from abcradabra (linked in above issue) https://github.com/nicoespeon/abracadabra/commit/10e0c3d0a5a5a88c01fae62b6bf92318d33f6bc1 https://github.com/nicoespeon/abracadabra

### CODE REVIEW

**Comment by iRyusa** [comment]
👋 Thanks for this, can you check to remove that .yarn stuff you've commited ?

**Comment by rosskevin** [comment]
Hey @iRyusa - I just pushed more changes, let me update the OP...one moment

**Comment by rosskevin** [comment]
@iRyusa I think this is good to review now.  I bumped the version just for safety, you can revert that or change as needed.

In our open repos, we always ship the .yarn stuff (no cache) so everyone is always on the same page.  I believe the script additions makes this feasible.

Of course you are free to change that, but I think the overall package now is buildable, packageable and deployable as long as long as someone is using a modern yarn.  

There are different ways to accomplish the same thing though...I'm just wanting to see this easily contributed to by many.

**Comment by rosskevin** [comment]
@iRyusa currently if you locally `package:install` the vsix - the plugin disappears - so not all is quite well.

**Comment by rosskevin** [comment]
Wondering if this needs to further similar to abcracadabra and use esbuild https://code.visualstudio.com/api/working-with-extensions/bundling-extension

?

**Comment by rosskevin** [comment]
`.yarn` is out, the ignores remain.

**Comment by rosskevin** [comment]
I'm going to leave this branch/PR as-is but branch from here and try the recommended esbuild path.

**Comment by rosskevin** [comment]
NOTE: the esbuild path is raising _good_ errors - showing things that will break at runtime (likely the problem) such as:

```
▲ [WARNING] Calling "mjml2html" will crash at run-time because it's an import namespace object, not a function [call-import-namespace]

    src/helper.ts:66:15:
      66 │         return mjml2html(mjml, {
```

so I'll keep pursuing that.

**Comment by rosskevin** [comment]
@iRyusa any chance you can try to run this and let me know where I should look to fix it?

**Comment by iRyusa** [comment]
I'm trying to get this merge and deployed today + some cleaning on the repo (removing phantomJS, MJML5,...)

**Review by iRyusa — APPROVED** [review]

**Comment by iRyusa** [comment]
@rosskevin Massive thanks for this I had to remove some of old deps that cause some issue (ESModule 😬)

This is published as 2.0.0 with MJML5 branch on it, and some older command are removed.
Again, sorry for the late merge and reply

**Pull request merged**
