### PR TITLE
Allow to preview partial MJML files

### PR DESCRIPTION
**Pull request by md-turismoi**
Previous version only allow to preview complete and well-formed MJML files (<mjml><mjml-body>....</mjml-body></mjml>). 
This version allows also to preview partial MJML files (<mjml-section>...</mjml-section>) to be able to create dynamic layouts splitting shared headers/footers in different files and include them in run-time.

`<mj-section>
    <mj-column>
            <mj-text>THIS IS A PREVIEW OF A PARTIAL MJML FILE !!!!</mj-text>
    </mj-column>
</mj-section>`

### CODE REVIEW

**Comment by Daniel-Knights** [comment]
Only issue with this is styles don't carry over, not sure if there's a way around that

**Comment by Daniel-Knights** [comment]
Also, if, on the off-chance, someone added a comment:

```
<!-- <mjml> -->
```

It wouldn't work.

Unlikely, but still a possibility.

**Comment by md-turismoi** [comment]
That's right.  <mj-style> tag don't carry over if there is no <mj-header>.

This feature was designed for scenarios where you have different kinds of emails in your project, you might want to extract some of the shared logic into something you could reuse (email header & footer, replacing dynamically only the body or some sections). In that case, the partial MJML files should not include the shared markups:
**baseLayout.mjml**
`<mjml>
  <mj-body>
    <mj-container>
      
      <%= render partial: 'foobar_header', formats: [:html] %>
  
      
      <mj-text>Hello <%= @name %></mj-text>
    </mj-container>
  </mj-body>
</mjml>`

**footer_header.mjml**
`<mj-section> 
      <mj-column> 
             <mj-text>THIS IS A PREVIEW OF A PARTIAL MJML FILE !!!!</mj-text> 
      </mj-column> 
 </mj-section>`

**Comment by kmcb777** [comment]
@md-turismoi Hi, thanks for this PR and sorry for the wait.
This is useful indeed, but in the mjml-app we have an equivalent feature to allow partials rendering, and we check it like this : ```if(documentText.trim().startsWith('<mjml'))```
I'd prefer it to be the same here, could you please just change this ?

**Pull request merged**
